# Generated by Django 4.2.2 on 2023-07-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(choices=[('S', 'Sublimasyon'), ('D', 'Dtf'), ('U', 'Uv')], default='S', max_length=1),
        ),
    ]
