# Generated by Django 4.2.2 on 2023-07-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_machine_machine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(choices=[('S', 'Süblimasyon'), ('D', 'Dtf'), ('U', 'Uv')], max_length=1),
        ),
    ]
