# Generated by Django 4.2.2 on 2023-07-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0002_alter_workorder_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='number_of_remained_amount',
            field=models.IntegerField(default=0),
        ),
    ]
