# Generated by Django 4.2.2 on 2023-07-09 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0003_workorder_number_of_remained_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='number_of_remained_amount',
            new_name='remained_amount',
        ),
    ]
