# Generated by Django 4.2.2 on 2023-07-14 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work_orders', '0004_rename_number_of_remained_amount_workorder_remained_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('process', models.CharField(max_length=200, unique=True)),
                ('remained_amount', models.IntegerField(default=0)),
                ('number_of_copy', models.DecimalField(decimal_places=1, max_digits=5)),
                ('number_of_remained_copy', models.DecimalField(decimal_places=1, max_digits=5)),
                ('log_date_time', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_by', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_orders.workorder')),
            ],
            options={
                'verbose_name_plural': 'İşlem Logları',
            },
        ),
    ]
