# Generated by Django 4.2.2 on 2023-07-14 19:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work_orders', '0004_rename_number_of_remained_amount_workorder_remained_amount'),
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProcessLogs',
            new_name='ProcessLog',
        ),
    ]
