# Generated by Django 4.2.2 on 2023-07-14 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0004_rename_number_of_remained_amount_workorder_remained_amount'),
        ('processes', '0004_remove_processlog_work_order_processlog_work_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processlog',
            name='process',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='processlog',
            name='remained_amount',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='processlog',
            name='work_order',
        ),
        migrations.AddField(
            model_name='processlog',
            name='work_order',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='work_orders.workorder'),
        ),
    ]
